package com.raise.nb.domain;

import java.time.LocalDateTime;

public class Todo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.todo_id
     *
     * @mbg.generated
     */
    private Integer todoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.todo_title
     *
     * @mbg.generated
     */
    private String todoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.finished
     *
     * @mbg.generated
     */
    private Boolean finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.todo_id
     *
     * @return the value of todo.todo_id
     *
     * @mbg.generated
     */
    public Integer getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.todo_id
     *
     * @param todoId the value for todo.todo_id
     *
     * @mbg.generated
     */
    public void setTodoId(Integer todoId) {
        this.todoId = todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.todo_title
     *
     * @return the value of todo.todo_title
     *
     * @mbg.generated
     */
    public String getTodoTitle() {
        return todoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.todo_title
     *
     * @param todoTitle the value for todo.todo_title
     *
     * @mbg.generated
     */
    public void setTodoTitle(String todoTitle) {
        this.todoTitle = todoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.finished
     *
     * @return the value of todo.finished
     *
     * @mbg.generated
     */
    public Boolean getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.finished
     *
     * @param finished the value for todo.finished
     *
     * @mbg.generated
     */
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.created_at
     *
     * @return the value of todo.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.created_at
     *
     * @param createdAt the value for todo.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo.updated_at
     *
     * @return the value of todo.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo.updated_at
     *
     * @param updatedAt the value for todo.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}